Fix: removed use of unittest.IsolatedAsyncioTestCase
unittest.IsolatedAsyncioTestCase was not removed within test_bforce.py of unit tests
while working on issue #25. It was left out by mistake while testing changes from corresponding
commit of the issue.

'AttributeError: module 'unittest' has no attribute 'IsolatedAsyncioTestCase'' was getting raised
when running integrated tests. The reason it was left out was that the tests were tested with python 3.8
instead of 3.6 which resulted in the exception not being raised.

Changes
-------
test_bforce.py - unittest.IsolatedAsyncioTestCase class was replaced by aiounittest.AsyncTestCase class.